interface ZIF_I_CLIMO_ERROR_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF Z_I_CLIMO_ERROR,
 CREATE_Z_I_CLIMO_ERROR         TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FE8432',
 DELETE_Z_I_CLIMO_ERROR         TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FF0432',
 LOCK_Z_I_CLIMO_ERROR           TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FDC432',
 SAVE_Z_I_CLIMO_ERROR           TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FF8432',
 UNLOCK_Z_I_CLIMO_ERROR         TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FE0432',
 UPDATE_Z_I_CLIMO_ERROR         TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FEC432',
 VALIDATE_Z_I_CLIMO_ERROR       TYPE /BOBF/ACT_KEY VALUE '080027A940B51EE899E785B259FF4432',
      END OF Z_I_CLIMO_ERROR,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF Z_I_CLIMO_ERROR,
        BEGIN OF LOCK_Z_I_CLIMO_ERROR,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_Z_I_CLIMO_ERROR,
        BEGIN OF UNLOCK_Z_I_CLIMO_ERROR,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_Z_I_CLIMO_ERROR,
      END OF Z_I_CLIMO_ERROR,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF Z_I_CLIMO_ERROR,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '080027A940B51EE899E785D727418432',
      END OF Z_I_CLIMO_ERROR,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF Z_I_CLIMO_ERROR,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027A940B51EE899E785B259FDA432',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027A940B51EE899E785B259FD6432',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027A940B51EE899E785B259FE6432',
      END OF Z_I_CLIMO_ERROR,
      BEGIN OF Z_I_CLIMO_ERROR_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027A940B51EE899E785B259FFE432',
      END OF Z_I_CLIMO_ERROR_LOCK,
      BEGIN OF Z_I_CLIMO_ERROR_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027A940B51EE899E785B259FFC432',
      END OF Z_I_CLIMO_ERROR_MESSAGE,
      BEGIN OF Z_I_CLIMO_ERROR_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027A940B51EE899E785B25A000432',
      END OF Z_I_CLIMO_ERROR_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF Z_I_CLIMO_ERROR,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF Z_I_CLIMO_ERROR,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '080027A940B51EE899E785B259FCC432' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'Z_I_CLIMO_ERROR' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 Z_I_CLIMO_ERROR                TYPE /BOBF/OBM_NODE_KEY VALUE '080027A940B51EE899E785B259FD0432',
 Z_I_CLIMO_ERROR_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '080027A940B51EE899E785B259FD8432',
 Z_I_CLIMO_ERROR_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '080027A940B51EE899E785B259FD4432',
 Z_I_CLIMO_ERROR_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '080027A940B51EE899E785B259FE4432',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF Z_I_CLIMO_ERROR,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  TYPE                           TYPE STRING VALUE 'TYPE',
  MESSAGE                        TYPE STRING VALUE 'MESSAGE',
  HOST_NAME                      TYPE STRING VALUE 'HOST_NAME',
  PORT                           TYPE STRING VALUE 'PORT',
  PATH_NAME                      TYPE STRING VALUE 'PATH_NAME',
  SEARCH                         TYPE STRING VALUE 'SEARCH',
  TIMESTAMP                      TYPE STRING VALUE 'TIMESTAMP',
  SOURCE                         TYPE STRING VALUE 'SOURCE',
  LINE_NO                        TYPE STRING VALUE 'LINE_NO',
  COL_NO                         TYPE STRING VALUE 'COL_NO',
  CLIENT_USER                    TYPE STRING VALUE 'CLIENT_USER',
      END OF Z_I_CLIMO_ERROR,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF Z_I_CLIMO_ERROR,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '080027A940B51EE899E785B259FD2432',
      END OF Z_I_CLIMO_ERROR,
    END OF SC_NODE_CATEGORY .
endinterface.
